server:
  port: 8090
spring:
  data:
    mongodb:
      username: cheikhibrambengue90
      password: cheikh
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin